# SEO settings
title: 유진로그
author: YujinGaya
description: >-
  개발, 디자인, 미식
url: "https://blog.yujingaya.com"
# author: 
twitter:
  username: yujinlog
# logo: /assets/logo.png
lang: ko_KR

minima:
  date_format: "%Y년 %m월 %d일"

# Header links
header_pages:
  - about.md

# Footer links
email: yujingaya@icloud.com
github_username: YujinGaya
twitter_username: yujinlog

baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-66130804-3

host: 0.0.0.0
