# SEO settings
title: 망상비축기지
author: YujinGaya
description: >-
  만약의 경우를 대비해 망상을 모아둡니다.
url: "https://blog.yujingaya.com"
# author: 
twitter:
  username: yujinlog
lang: ko_KR

minima:
  date_format: "%Y년 %m월 %d일"

# Header links
header_pages:
  - about.md

# Footer links
email: yujingaya@icloud.com
github_username: YujinGaya
twitter_username: yujinlog

baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-66130804-3

host: 0.0.0.0
